services:
  postgres:
    image: postgres:16
    container_name: bibliobus_db
    environment:
      POSTGRES_DB: libdb
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ../data/raw:/data/raw:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d libdb"]
      interval: 10s
      timeout: 5s
      retries: 5
